name: Run Aarav Bot

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"   # Har 10 minute me run (keep alive)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Repo Clone
        uses: actions/checkout@v4

      - name: 🟢 Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🚀 Start Bot
        run: node index.js
